// ===================  Country + User ID ===================
const dropdown=document.getElementById("countryDropdown");const selected=dropdown?dropdown.querySelector(".selected"):null;const options=dropdown?dropdown.querySelector(".options"):null;let toast=document.getElementById("country-toast");if(!toast){toast=document.createElement("div");toast.id="country-toast";document.body.appendChild(toast)}
const url=new URL(window.location.href);const paramCountry=url.searchParams.get("country");const savedCountry=localStorage.getItem("Cntry");let activeCountry=null;function setActiveCountry(code,updateUrl=!0){if(!options)return;const li=options.querySelector(`li[data-value="${code}"]`);if(!li)return;activeCountry=code;localStorage.setItem("Cntry",code);if(selected)selected.innerHTML=li.innerHTML;if(updateUrl){url.searchParams.set("country",code);window.history.replaceState({},"",url)}}
if(paramCountry){setActiveCountry(paramCountry)}else if(savedCountry){setActiveCountry(savedCountry)}else{setActiveCountry("SA")}
if(selected&&dropdown&&options){selected.addEventListener("click",()=>{dropdown.classList.toggle("open");options.style.display=dropdown.classList.contains("open")?"block":"none"});options.addEventListener("click",(e)=>{const li=e.target.closest("li");if(!li)return;const countryCode=li.getAttribute("data-value");setActiveCountry(countryCode);showToast("تم اختيار: "+li.textContent.trim());setTimeout(()=>{window.location.reload()},500)});document.addEventListener("click",(e)=>{if(!dropdown.contains(e.target)){dropdown.classList.remove("open");options.style.display="none"}})}
function showToast(msg){if(!toast)return;toast.textContent=msg;toast.classList.add("show");setTimeout(()=>{toast.classList.remove("show")},1000)}
const canonical=document.createElement("link");canonical.rel="canonical";canonical.href=window.location.origin+window.location.pathname;document.head.appendChild(canonical);if(paramCountry){const robots=document.createElement("meta");robots.name="robots";robots.content="noindex";document.head.appendChild(robots)}

const UIDManager={generate(){const now=new Date();const datePart=now.getFullYear().toString()+(now.getMonth()+1).toString().padStart(2,'0')+now.getDate().toString().padStart(2,'0')+now.getHours().toString().padStart(2,'0')+now.getMinutes().toString().padStart(2,'0')+now.getSeconds().toString().padStart(2,'0');const randomPart=Math.random().toString(36).substring(2,10).toUpperCase();return `ID-${datePart}-${randomPart}`},getPersistentId(){let id=localStorage.getItem("user_fingerprint");if(!id){id=this.generate();localStorage.setItem("user_fingerprint",id)}
return id}}

window.userVerifySync = function(s) {
    return s.split('').map(c => String.fromCharCode(c.charCodeAt(0) - 10)).join('');
};

// =================== Cart ===================
function updateCartWidget(){const cart=JSON.parse(localStorage.getItem("cart"))||[];const cartCountElement=document.getElementById("cart-count");if(!cartCountElement)return;cartCountElement.textContent=cart.length;if(cart.length>0){cartCountElement.classList.add("active")}else{cartCountElement.classList.remove("active")}}
updateCartWidget();window.addEventListener("storage",function(event){if(event.key==="cart"){updateCartWidget()}});window.addEventListener("cartUpdated",updateCartWidget);const cartWidget=document.getElementById("cart-widget-header");if(cartWidget){cartWidget.addEventListener("click",function(){window.location.href="/p/cart.html"})}

function showCartToast(m,t="success"){const h=document.createElement("div");document.body.prepend(h);const s=h.attachShadow({mode:"open"}),d=document.createElement("div");d.textContent=m;s.appendChild(d);const st=document.createElement("style");st.textContent=`div{position:fixed;top:20px;right:20px;min-width:220px;max-width:320px;background:${t==="error"?"#e74c3c":"#2ecc71"};color:white;font-family:sans-serif;font-size:14px;padding:12px 18px;border-radius:10px;box-shadow:0 4px 12px rgba(0,0,0,0.2);opacity:0;transform:translateX(120%);transition:all 0.4s ease;z-index:1000000;}div.show{opacity:1;transform:translateX(0);}`;s.appendChild(st);setTimeout(()=>d.classList.add("show"),50);setTimeout(()=>{d.classList.remove("show");setTimeout(()=>h.remove(),400)},3000)}
function addToCart(id){if(!id){showCartToast("عذراً، لم يتم العثور على معرف المنتج!","error");return}let c=JSON.parse(localStorage.getItem("cart"))||[];if(c.some(i=>i.id===id)){showCartToast("المنتج موجود بالفعل في العربة!","error");return}c.push({id:id,timestamp:new Date().getTime()});localStorage.setItem("cart",JSON.stringify(c));window.dispatchEvent(new Event("cartUpdated"));showCartToast("تمت إضافة المنتج بنجاح!","success")}
document.addEventListener("click",function(e){const b=e.target.closest(".external-cart-button");if(b){e.preventDefault();e.stopPropagation();const p=e.target.closest(".post-card");const id=p?p.querySelector(".UID")?.textContent.trim():null;addToCart(id)}const a=e.target.closest(".add-to-cart");if(a){e.preventDefault();e.stopPropagation();const u=document.querySelector(".UID");addToCart(u?u.textContent.trim():null)}});

// =================== Share + SEO  ===================
document.addEventListener('DOMContentLoaded',function(){var modal=document.querySelector('.share-modal');var openBtn=document.querySelector('.share-open-btn');var closeBtn=document.querySelector('.modal-close-btn');if(modal&&openBtn&&closeBtn){openBtn.onclick=function(){modal.style.display='block';document.body.style.overflow='hidden'}
closeBtn.onclick=function(){modal.style.display='none';document.body.style.overflow='auto'}
window.onclick=function(event){if(event.target==modal){modal.style.display='none';document.body.style.overflow='auto'}}}})

function rmurl(e,t){var r=new RegExp(/\?m=0|&m=0|\?m=1|&m=1/g);if(r.test(e)){e=e.replace(r,"");if(t)window.history.replaceState({},document.title,e)}
return e}
const currentUrl=rmurl(location.toString(),!0)

// =================== DM + Back To Top  ===================
var htmlEl=document.documentElement,darkBtn=document.getElementById("dark-toggler"),iconUse=darkBtn ? darkBtn.querySelector("use") :null;function switchIcon(theme){if(!iconUse) return;if(theme==="dark"){iconUse.setAttribute("xlink:href","#i-sun");iconUse.setAttribute("href","#i-sun")}else{iconUse.setAttribute("xlink:href","#i-moon");iconUse.setAttribute("href","#i-moon")}}function applyTheme(theme,persist){if(theme==="dark"){htmlEl.classList.add("dark-mode");htmlEl.setAttribute("data-theme","dark")}else{htmlEl.classList.remove("dark-mode");htmlEl.setAttribute("data-theme","light")}switchIcon(theme);if(persist){try{localStorage.setItem("theme",theme)}catch(e){}}}var savedTheme;try{savedTheme=localStorage.getItem("theme")}catch(e){savedTheme=null}if(!savedTheme){savedTheme=window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark":"light"}applyTheme(savedTheme,false);if(darkBtn){darkBtn.addEventListener("click",function(e){e.preventDefault();var isDark=htmlEl.classList.contains("dark-mode");applyTheme(isDark ? "light":"dark",true)})}

var backTop = document.getElementById("back-to-top");
window.addEventListener("scroll",function(){
  if(!backTop) return;
  if(this.pageYOffset >= 1000){
    backTop.classList.remove("d-none");
  } else {
    backTop.classList.add("d-none");
  }
},false);

// =================== Track ===================
(function(){const _0x4a21="aHR0cHM6Ly9zY3JpcHQuZ29vZ2xlLmNvbS9tYWNyb3Mvcy9BS2Z5Y2J5OHhPVTRFeXJzUElsLWhGMC1QeVVFMmdEQnFLRC1kc05JVGROYTNkY0dnOVVUOVVqMEJmU01rZ1Y0dDNfa0ZVTUU2dy9leGVj";const webAppUrl=atob(_0x4a21);let actionsList=["Entry"];let exitUrl="Closed Tab/Direct";let isSent=!1;setTimeout(()=>{const visitorId=(typeof UIDManager!=='undefined')?UIDManager.getPersistentId():"Unknown";const getCleanUrl=(url)=>{if(!url)return"";return url.replace("https://iseekprice.blogspot.com","")||"/"};const detectOS=()=>{const ua=navigator.userAgent;if(/Android/i.test(ua))return"Android";if(/iPhone|iPad|iPod/i.test(ua))return"iOS";if(/Win/i.test(ua))return"Windows";if(/Mac/i.test(ua))return"MacOS";return"Linux/Other"};const prepareData=()=>{const ua=navigator.userAgent.toLowerCase();const{width,height}=window.screen;let browser=ua.includes("edg")?"Edge":ua.includes("opr")?"Opera":ua.includes("chrome")?"Chrome":ua.includes("firefox")?"Firefox":"Safari";return JSON.stringify({entryTime:new Date().toLocaleString('sv-SE'),visitorId:visitorId,action:actionsList.join(" -> "),pageUrl:getCleanUrl(window.location.href),referrer:document.referrer||"Direct Search",exitDestination:exitUrl,os:detectOS(),browser:browser,screenRes:`${width}x${height}`,token:"SECURE_BY_DOMAIN"})};const sendFinalData=()=>{if(isSent||actionsList.length===0)return;const data=prepareData();if(navigator.sendBeacon){navigator.sendBeacon(webAppUrl,data)}else{fetch(webAppUrl,{method:'POST',body:data,keepalive:!0})}
isSent=!0};document.addEventListener("mousedown",(e)=>{const target=e.target.closest("a, .buy-button, .add-to-cart, .copy-button, .tab-buttons button");if(!target)return;if(target.tagName==="A"){if(target.href&&!target.href.includes("iseekprice.blogspot.com")&&!target.href.startsWith("javascript")){exitUrl=target.href;if(!actionsList.includes("Exit Click"))actionsList.push("Exit Click");}}else{let label="";if(target.classList.contains("buy-button"))label="Buy";else if(target.classList.contains("add-to-cart"))label="Cart";else if(target.classList.contains("copy-button"))label="Coupon";else label="T:"+target.innerText.trim().substring(0,10);if(label&&!actionsList.includes(label))actionsList.push(label);}});window.addEventListener("pagehide",sendFinalData);window.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")sendFinalData();})},3500)})()
