// =================== Theme-Script.js ===================

const searchPageURL="https://souq-alkul.blogspot.com/p/search.html";const input=document.getElementById("searchInput");const form=document.querySelector(".search-box-form");const historyDropdown=document.getElementById("searchHistoryDropdown");let searches=JSON.parse(localStorage.getItem('searches'))||[];function updateDropdown(){historyDropdown.innerHTML='';let toShow=searches.slice(0,5);if(toShow.length===0){historyDropdown.style.display='none';return}
toShow.forEach(term=>{let item=document.createElement('div');let text=document.createElement('span');text.textContent=term;text.addEventListener('click',()=>{input.value=term;historyDropdown.style.display='none'});let del=document.createElement('span');del.textContent='×';del.classList.add('delete-btn');del.addEventListener('click',(e)=>{e.stopPropagation();searches=searches.filter(t=>t!==term);localStorage.setItem('searches',JSON.stringify(searches));updateDropdown()});item.appendChild(text);item.appendChild(del);historyDropdown.appendChild(item)});historyDropdown.style.display='block'}
function startSearch(){if(!input)return;const query=input.value.trim();if(query){searches=searches.filter(t=>t!==query);searches.unshift(query);if(searches.length>10)searches=searches.slice(0,10);localStorage.setItem('searches',JSON.stringify(searches));window.location.href=`${searchPageURL}?q=${encodeURIComponent(query)}`}}
if(form){form.addEventListener("submit",function(e){e.preventDefault();startSearch()})}
if(input){input.addEventListener('focus',updateDropdown)}
document.addEventListener('click',(e)=>{if(!e.target.closest('.search-container')){historyDropdown.style.display='none'}});if(input){const placeholders=["ماكينة قهوة ديلونجي","سماعات بلوتوث جالكسي بودز","مكنسة روبوت ذكية","شاحن مغناطيسي للآيفون","ستاند لابتوب قابل للطي","مكواة بخار محمولة","عصارة فواكه كهربائية","كاميرا مراقبة واي فاي","ماوس لاسلكي لابتوب","منظف وجه كهربائي","لوح مفاتيح ميكانيكي RGB","فرامة خضار يدوية","ميزان ذكي للحمية","سماعات رأس للألعاب","ساعة ذكية شاومي","ترايبود كاميرا احترافي","كشاف LED قابل للشحن","دفاية كهربائية صغيرة","مروحة USB مكتبية","عطر عربي فاخر","شاحن متنقل باور بانك","شنطة لابتوب ضد الماء","كرسي ألعاب مريح","سماعات نويس كانسل","خلاط يدوي متعدد الاستخدام","مقص مطبخ ستانلس ستيل","مظلة أوتوماتيكية","فلاش ميموري سريع","مقلاة هوائية صحية","كاميرا فورية بولارويد","ميزان مطبخ رقمي","مبخرة منزلية كهربائية","ترموس حافظ للحرارة","زجاجة ماء ذكية","مصباح مكتب LED","مروحة محمولة باليد","شاحن جداري سريع","منظم أسلاك مكتب","صندوق تخزين بلاستيك","سماعة مكالمات بلوتوث","منقي هواء صغير","سخان ماء كهربائي","دفتر ملاحظات ذكي","قفل بصمة ذكي","موزع صابون أوتوماتيكي","منظم درج ملابس","مقعد أرضي مريح","كوب قهوة حراري","لوحة مفاتيح لاسلكية","مفرمة لحوم كهربائية","أداة تقطيع بطاطس","صانعة فشار منزلية","طقم ملاعق قياس","جهاز قياس حرارة رقمي","منبه مكتبي كلاسيكي","طابعة صور ملونة","لابتوب أسوس","جوال شاومي ريدمي","تابلت سامسونج جالكسي","حقيبة ظهر للطلاب","قرص صلب خارجي","كابل شحن تايب سي","ماوس جيمينج","مكواة شعر سيراميك","عصا سيلفي بلوتوث","آلة حاسبة علمية","سماعة رأس سلكية","دفاية زيت كهربائية","طقم مفكات متعدد","مقص أظافر ستانلس","ابحث في سوق الكل"];function getRandomPlaceholder(){const randomIndex=Math.floor(Math.random()*placeholders.length);return placeholders[randomIndex]}
function rotatePlaceholder(){if(placeholders.length>0){input.setAttribute("placeholder",getRandomPlaceholder())}}
rotatePlaceholder();setInterval(rotatePlaceholder,25000)}
function updateCartWidget(){const cart=JSON.parse(localStorage.getItem("cart"))||[];const cartCountElement=document.getElementById("cart-count");if(!cartCountElement)return;cartCountElement.textContent=cart.length;if(cart.length>0){cartCountElement.classList.add("active")}else{cartCountElement.classList.remove("active")}}
updateCartWidget();window.addEventListener("storage",function(event){if(event.key==="cart"){updateCartWidget()}});window.addEventListener("cartUpdated",updateCartWidget);const cartWidget=document.getElementById("cart-widget-header");if(cartWidget){cartWidget.addEventListener("click",function(){window.location.href="/p/cart.html"})}
var htmlEl=document.documentElement,darkBtn=document.getElementById("dark-toggler"),iconUse=darkBtn?darkBtn.querySelector("use"):null;function switchIcon(theme){if(!iconUse)return;if(theme==="dark"){iconUse.setAttribute("xlink:href","#i-sun");iconUse.setAttribute("href","#i-sun")}else{iconUse.setAttribute("xlink:href","#i-moon");iconUse.setAttribute("href","#i-moon")}}
function applyTheme(theme,persist){if(theme==="dark"){htmlEl.classList.add("dark-mode");htmlEl.setAttribute("data-theme","dark")}else{htmlEl.classList.remove("dark-mode");htmlEl.setAttribute("data-theme","light")}
switchIcon(theme);if(persist){try{localStorage.setItem("theme",theme)}catch(e){}}}
var savedTheme;try{savedTheme=localStorage.getItem("theme")}catch(e){savedTheme=null}
if(!savedTheme){savedTheme=window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}
applyTheme(savedTheme,!1);if(darkBtn){darkBtn.addEventListener("click",function(e){e.preventDefault();var isDark=htmlEl.classList.contains("dark-mode");applyTheme(isDark?"light":"dark",!0)})}
const dropdown=document.getElementById("countryDropdown");const selected=dropdown?dropdown.querySelector(".selected"):null;const options=dropdown?dropdown.querySelector(".options"):null;let toast=document.getElementById("country-toast");if(!toast){toast=document.createElement("div");toast.id="country-toast";document.body.appendChild(toast)}
const url=new URL(window.location.href);const paramCountry=url.searchParams.get("country");const savedCountry=localStorage.getItem("Cntry");let activeCountry=null;function setActiveCountry(code,updateUrl=!0){if(!options)return;const li=options.querySelector(`li[data-value="${code}"]`);if(!li)return;activeCountry=code;localStorage.setItem("Cntry",code);if(selected)selected.innerHTML=li.innerHTML;if(updateUrl){url.searchParams.set("country",code);window.history.replaceState({},"",url)}}
if(paramCountry){setActiveCountry(paramCountry)}else if(savedCountry){setActiveCountry(savedCountry)}else{setActiveCountry("SA")}
if(selected&&dropdown&&options){selected.addEventListener("click",()=>{dropdown.classList.toggle("open");options.style.display=dropdown.classList.contains("open")?"block":"none"});options.addEventListener("click",(e)=>{const li=e.target.closest("li");if(!li)return;const countryCode=li.getAttribute("data-value");setActiveCountry(countryCode);showToast("تم اختيار: "+li.textContent.trim());setTimeout(()=>{window.location.reload()},500)});document.addEventListener("click",(e)=>{if(!dropdown.contains(e.target)){dropdown.classList.remove("open");options.style.display="none"}})}
function showToast(msg){if(!toast)return;toast.textContent=msg;toast.classList.add("show");setTimeout(()=>{toast.classList.remove("show")},1000)}
const canonical=document.createElement("link");canonical.rel="canonical";canonical.href=window.location.origin+window.location.pathname;document.head.appendChild(canonical);if(paramCountry){const robots=document.createElement("meta");robots.name="robots";robots.content="noindex";document.head.appendChild(robots)}
document.addEventListener('DOMContentLoaded',function(){var modal=document.querySelector('.share-modal');var openBtn=document.querySelector('.share-open-btn');var closeBtn=document.querySelector('.modal-close-btn');if(modal&&openBtn&&closeBtn){openBtn.onclick=function(){modal.style.display='block';document.body.style.overflow='hidden'}
closeBtn.onclick=function(){modal.style.display='none';document.body.style.overflow='auto'}
window.onclick=function(event){if(event.target==modal){modal.style.display='none';document.body.style.overflow='auto'}}}});const UIDManager={generate(){const now=new Date();const datePart=now.getFullYear().toString()+(now.getMonth()+1).toString().padStart(2,'0')+now.getDate().toString().padStart(2,'0')+now.getHours().toString().padStart(2,'0')+now.getMinutes().toString().padStart(2,'0')+now.getSeconds().toString().padStart(2,'0');const randomPart=Math.random().toString(36).substring(2,10).toUpperCase();return `ID-${datePart}-${randomPart}`},getPersistentId(){let id=localStorage.getItem("user_fingerprint");if(!id){id=this.generate();localStorage.setItem("user_fingerprint",id)}
return id}};function rmurl(e,t){var r=new RegExp(/\?m=0|&m=0|\?m=1|&m=1/g);if(r.test(e)){e=e.replace(r,"");if(t)window.history.replaceState({},document.title,e)}
return e}
const currentUrl=rmurl(location.toString(),!0);var backTop=document.getElementById("back-to-top");window.addEventListener("scroll",function(){if(!backTop)return;if(this.pageYOffset>=1000){backTop.classList.remove("d-none")}else{backTop.classList.add("d-none")}},!1)

// =================== Nav.js ===================

document.addEventListener('DOMContentLoaded',()=>{const categories=[{name:'إلكترونيات',children:[{name:'جوالات',children:[{name:'شاومي'},{name:'سامسونج'},{name:'آيفون'},{name:'أوبو'},{name:'هواوي'}]},{name:'لابتوبات',children:[{name:'جيمينج'},{name:'ماك بوك'},{name:'لابتوبات أعمال'}]},{name:'شاشات',children:[{name:'شاشات ذكية'},{name:'شاشات كمبيوتر'}]}]},{name:'أدوات منزلية',children:[{name:'المطبخ',children:[{name:'خلاطات'},{name:'مكاوي'},{name:'ماكينات قهوة'},{name:'أفران كهربائية'}]},{name:'التنظيف',children:[{name:'مكانس كهربائية'},{name:'غسالات'}]}]},{name:'ملحقات',children:[{name:'سماعات'},{name:'كيبورد وماوس'},{name:'باور بانك'}]},{name:'ألعاب',children:[{name:'بلاي ستيشن'},{name:'إكس بوكس'},{name:'نينتندو سويتش'}]},{name:'عروض خاصة'},{name:'الموضة'},{name:'المنزل والمطبخ'},{name:'أجهزة صغيرة'},{name:'الصحة والجمال'}];function generateLink(cat){const base="https://souq-alkul.blogspot.com/p/search.html";return `${base}?label=${encodeURIComponent(cat.name)}`}
const toggleBtn=document.getElementById('widget-toggle-btn');const closeBtn=document.getElementById('widget-close-btn');const sidebar=document.getElementById('widget-sidebar');const overlay=document.getElementById('widget-overlay');const sideList=document.getElementById('widget-side-list');const desktopCats=document.getElementById('widget-desktop-cats');const sidebarTitle=document.getElementById('widget-sidebar-title');categories.slice(0,5).forEach(cat=>{const wrapper=document.createElement('div');wrapper.className='widget-cat-wrapper';const link=document.createElement('a');link.textContent=cat.name;link.href=generateLink(cat);link.className='widget-cat-link';link.addEventListener('mouseover',()=>link.style.setProperty("--underline-scale","1"));link.addEventListener('mouseout',()=>link.style.setProperty("--underline-scale","0"));wrapper.appendChild(link);if(cat.children){const expandBtn=document.createElement('span');expandBtn.textContent='❯';expandBtn.className='widget-expand-btn';expandBtn.addEventListener('click',(e)=>{e.preventDefault();openSidebar(!1);renderSubCategories(cat.name,cat.children||[])});wrapper.appendChild(expandBtn)}
desktopCats.appendChild(wrapper)});function createCategoryRow(cat){const row=document.createElement('div');row.className='widget-category-row';const link=document.createElement('a');link.textContent=cat.name;link.href=generateLink(cat);row.appendChild(link);if(cat.children){const expandBtn=document.createElement('span');expandBtn.textContent='❯';expandBtn.className='widget-expand-btn-sidebar';expandBtn.addEventListener('click',(e)=>{e.preventDefault();renderSubCategories(cat.name,cat.children)});row.appendChild(expandBtn)}
return row}
function renderMainCategories(){sideList.innerHTML="";sidebarTitle.textContent='التصنيفات';categories.forEach(cat=>sideList.appendChild(createCategoryRow(cat)))}
function renderSubCategories(title,children){sideList.innerHTML="";sidebarTitle.textContent=title;const backRow=document.createElement('div');backRow.textContent='← رجوع';backRow.className='widget-back-row';backRow.addEventListener('click',()=>renderMainCategories());sideList.appendChild(backRow);children.forEach(sub=>sideList.appendChild(createCategoryRow(sub)))}
function openSidebar(showMain=!0){sidebar.style.right='0';overlay.style.display='block';if(showMain)renderMainCategories();}
function closeSidebar(){sidebar.style.right='-300px';overlay.style.display='none'}
toggleBtn.addEventListener('click',()=>openSidebar(!0));closeBtn.addEventListener('click',closeSidebar);overlay.addEventListener('click',closeSidebar);function applyResponsive(){if(window.innerWidth>768){desktopCats.style.display='flex'}}
applyResponsive();window.addEventListener('resize',applyResponsive)})



